'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddMeeting

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MTitle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''MDateD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MDateD As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''MDateM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MDateM As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''MDateY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MDateY As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''MTimeM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MTimeM As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''MTimeH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MTimeH As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''MembersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MembersList As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''MembersListID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MembersListID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AddMeeting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddMeeting As Global.System.Web.UI.WebControls.Button
End Class
