'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewMeeting

    '''<summary>
    '''MTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MDo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MDo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Memb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Memb As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PMemb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PMemb As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UMemb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UMemb As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
